- name: Transfer-only execution speed
  description: Transfer-only execution speed
  variables:
    - type: transaction_workload
      values:
        - transfer-only
    - type: node_type
      values:
        - geth
        - reth
    - type: num_blocks
      value: 10
    - type: gas_limit
      values:
        - 15000000
        - 30000000
        - 60000000
        - 90000000